const express = require('express')
const userController = require('../Controllers/userController')
const auth = require('../Middlewere/auth')
const postController = require('../Controllers/postController')
const router = express.Router()

router.get('/', auth.verify, userController.homeView)
router.get('/notifications', auth.verify, userController.getNotification)
router.get('/follwers', auth.verify, userController.followersList)
router.get('/followings', auth.verify, userController.followingsList)
router.get('/profile', userController.profile)
router.post('/signUp', userController.userSignup)
router.post('/login', userController.login)
router.post('/googleLogin', userController.googleLogin)
router.get('/suggestedList', auth.verify, userController.suggestedList)
router.patch('/follow', auth.verify, userController.followHandle)
router.patch('/unfollow', auth.verify, userController.unfollowHandle)
router.get('/getDetails', auth.verify, userController.getDetails)
router.post('/like', auth.verify, postController.handleLike)
router.post('/comment', auth.verify, postController.handleComment)
router.patch('/reply', postController.replyComment)
router.patch('/likeComment', postController.likeComment)
router.patch('/savePost', userController.savepost)
router.post('/reportPost', auth.verify, postController.reportPost)
router.patch('/reportUser', auth.verify, userController.reportUser)
router.patch('/editProfile', auth.verify, userController.editProfilePic)
router.post('/addpost', auth.verify, postController.addPost)
router.get('/explore', auth.verify, postController.handleExplore)
router.get('/products', auth.verify, userController.GetProducts)
router.post('/AddProduct', auth.verify, userController.Addproduct)
router.get('/getChats', auth.verify, userController.getChats)
router.get('/getSingleChat', auth.verify, userController.getSingleChats)
router.get('/getMessages', auth.verify, userController.getMessages)
router.post('/sendMessage', auth.verify, userController.sendMessage)
router.post('/addStatus',postController.addStatus)
router.get('/search',userController.searchUser)
module.exports = router